### ISSUE TITLE
How is that working?

### ISSUE THREAD

**Issue by cuteskater** [waliarubal/ChaturbatePlayer#1]
Hey Friend,

how can i get this work? Can u help me?

**Comment by waliarubal** [comment]
Hello @cutestaker, I will be releasing installation setup tonight which you will be able to see in releases section. I’ll add a comment to keep you updated.

**Comment by waliarubal** [comment]
Sorry, misspelled your github handle @cuteskater.

**Comment by cuteskater** [comment]
Ohh thats cool. Nice work and nice too :-) I have writen u an email too lol

**Comment by waliarubal** [comment]
I have added installation setup to [releases page](https://github.com/waliarubal/ChaturbatePlayer/releases/latest).
